name: Event
description: Create an incoming event for the community
title: "<EVENT TITLE>"
labels: [incoming-event]
body:
  - type: input
    id: name
    attributes:
      label: Event Title
    validations:
      required: true
  - type: input
    id: date
    attributes:
      label: Event Date
    validations:
      required: true
  - type: input
    id: description
    attributes:
      label: Event description
    validations:
      required: true
  - type: textarea
    id: event-poster
    attributes:
      label: Event Poster 
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this event! If you need real-time help, please contact the community manager..
